// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvWMd3v0DtwoBA-Z3iujQiCnL9eYoPhCE',
    appId: '1:228136050809:web:ae3767e49d3fd3d832f4a8',
    messagingSenderId: '228136050809',
    projectId: 'autoease-438d7',
    authDomain: 'autoease-438d7.firebaseapp.com',
    storageBucket: 'autoease-438d7.appspot.com',
    measurementId: 'G-7RVQ72BCB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbAktm9IlAL4uEdak0mYD16iChpo6NmKw',
    appId: '1:228136050809:android:7eff666ef037d7d832f4a8',
    messagingSenderId: '228136050809',
    projectId: 'autoease-438d7',
    storageBucket: 'autoease-438d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxD7QS4HwuVc9LeugD9iYHZgj84qDfp9s',
    appId: '1:228136050809:ios:4e6d9e371ac44ef932f4a8',
    messagingSenderId: '228136050809',
    projectId: 'autoease-438d7',
    storageBucket: 'autoease-438d7.appspot.com',
    iosBundleId: 'com.example.autoEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxD7QS4HwuVc9LeugD9iYHZgj84qDfp9s',
    appId: '1:228136050809:ios:4e6d9e371ac44ef932f4a8',
    messagingSenderId: '228136050809',
    projectId: 'autoease-438d7',
    storageBucket: 'autoease-438d7.appspot.com',
    iosBundleId: 'com.example.autoEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvWMd3v0DtwoBA-Z3iujQiCnL9eYoPhCE',
    appId: '1:228136050809:web:d786a7a39f5208af32f4a8',
    messagingSenderId: '228136050809',
    projectId: 'autoease-438d7',
    authDomain: 'autoease-438d7.firebaseapp.com',
    storageBucket: 'autoease-438d7.appspot.com',
    measurementId: 'G-7484SGZ10R',
  );
}
